name: meshcore_dart
description: A Dart library for controlling MeshCore devices.
version: 0.1.5
repository: https://github.com/wel97459/meshcore.dart

environment:
  sdk: ^3.0.0

dependencies:
  cryptography: ^2.9.0
  flutter_libserialport: ^0.6.0
  libserialport: ^0.3.0+1
  libserialport_plus: ^0.0.12
  universal_ble: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0